print("Macam macam type data")
print("1. Boolean \nMenyatakan benar True yang bernilai 1, atau salah False yang bernilai 0\ncontoh : True atau False")
print("2. String \nMenyatakan karakter/kalimat bisa berupa huruf angka, dll (diapit tanda petik) \ncontoh : 'Ayo belajar Python'")
print("3. Integer \nMenyatakan bilangan bulat \ncontoh : 25 atau 1209")
print("4. Float \nMenyatakan bilangan yang mempunyai koma \ncontoh : 3.14 atau 0.99")
